# Generated by Django 4.1 on 2022-11-24 10:58

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nbm',
            field=models.CharField(max_length=13, validators=[order.models.telephone_validator], verbose_name='Number'),
        ),
    ]
