# Generated by Django 4.1 on 2022-11-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_state_city_order_city_alter_order_state'),
        ('account', '0002_alter_user_nbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adres',
            field=models.CharField(default='Some Adres', max_length=255, verbose_name='Adres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='order.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='post_ind',
            field=models.CharField(default='sddsds', max_length=6, verbose_name='Post Index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='order.state'),
            preserve_default=False,
        ),
    ]
