# Generated by Django 4.1 on 2022-11-27 12:55

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nbm',
            field=models.CharField(max_length=13, unique=True, validators=[order.models.telephone_validator], verbose_name='Number'),
        ),
    ]
