# Generated by Django 4.1 on 2022-11-30 16:34

import account.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='666666', max_length=6, verbose_name='Verify code'),
            preserve_default=False,
        ),
    ]
