# Generated by Django 4.1 on 2022-12-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_verify',
            field=models.BooleanField(default=False, verbose_name='Password verify'),
        ),
    ]
