# Generated by Django 4.1 on 2022-12-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_password_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_verify',
        ),
    ]
