# Generated by Django 4.1 on 2022-11-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='main.colors'),
            preserve_default=False,
        ),
    ]
