# Generated by Django 4.1 on 2022-11-24 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_colors_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Rating'),
        ),
    ]
