# Generated by Django 4.1 on 2022-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='atributs',
            field=models.ManyToManyField(null=True, to='main.atibuts'),
        ),
    ]
