# Generated by Django 4.1 on 2022-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_category_atributs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='hit',
            field=models.BooleanField(default=False, verbose_name='Is Hit Product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='atributs',
            field=models.ManyToManyField(blank=True, null=True, to='main.atibuts'),
        ),
    ]
