# Generated by Django 4.1 on 2022-11-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_products_category_products_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atibuts',
            new_name='Atributs',
        ),
    ]
