# Generated by Django 4.1 on 2022-11-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_products_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(default='Cougar', max_length=255, verbose_name='Manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(default='mxz-260', max_length=255, verbose_name='Model'),
            preserve_default=False,
        ),
    ]
