# Generated by Django 4.1 on 2022-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_products_manufacturer_products_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='options',
            field=models.ManyToManyField(to='main.atributoptions'),
        ),
    ]
