# Generated by Django 4.1 on 2022-11-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_productvariants_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
    ]
