# Generated by Django 4.1 on 2022-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_comments_rating_alter_productvariants_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='options',
            field=models.ManyToManyField(blank=True, to='main.atributoptions'),
        ),
    ]
