# Generated by Django 4.1 on 2022-11-26 19:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_productvariants_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='information',
            field=ckeditor.fields.RichTextField(default='dsdsd'),
            preserve_default=False,
        ),
    ]
