# Generated by Django 4.1 on 2022-11-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_products_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_of_day',
            field=models.BooleanField(default=False, verbose_name='Product of day'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.category'),
        ),
    ]
