# Generated by Django 4.1 on 2022-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='hit',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='popular',
        ),
        migrations.AddField(
            model_name='products',
            name='hit',
            field=models.BooleanField(default=False, verbose_name='Is Hit Product'),
        ),
        migrations.AddField(
            model_name='products',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AlterField(
            model_name='category',
            name='atributs',
            field=models.ManyToManyField(blank=True, null=True, to='main.atributs'),
        ),
    ]
