# Generated by Django 4.1 on 2022-12-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_productvariants_hit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='popular',
        ),
    ]
