# Generated by Django 4.1 on 2022-12-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_brand_remove_category_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
        ),
    ]
