# Generated by Django 4.1 on 2022-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_products_manufacturer_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
    ]
