# Generated by Django 4.1 on 2022-12-09 07:40

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_brand_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='brnad'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.brand'),
        ),
    ]
