# Generated by Django 4.1 on 2022-12-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_brand_image_alter_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='prod_of_day',
        ),
        migrations.AddField(
            model_name='productvariants',
            name='prod_of_day',
            field=models.BooleanField(default=False, verbose_name='Product of day'),
        ),
    ]
