# Generated by Django 4.1 on 2022-12-11 09:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_products_prod_of_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='matching',
            field=ckeditor.fields.RichTextField(default='Some text'),
            preserve_default=False,
        ),
    ]
