# Generated by Django 4.1 on 2022-12-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_productvariants_matching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Published', 'Published')], default='Inactive', max_length=255, verbose_name='Status'),
        ),
    ]
