# Generated by Django 4.1 on 2022-12-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
