# Generated by Django 4.1 on 2022-11-23 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255, verbose_name='Session Key')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Price')),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=255, verbose_name='Payment type')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Patronymic')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres')),
                ('state', models.CharField(choices=[('Андижанская область', 'Андижанская область'), ('Бухарская область   ', 'Бухарская область   '), ('Джизакская область ', 'Джизакская область '), ('Кашкадарьинская область  ', 'Кашкадарьинская область  '), ('Навоийская область', 'Навоийская область'), ('Наманганская область', 'Наманганская область'), ('Самаркандская область   ', 'Самаркандская область'), ('Сурхандарьинская область   ', 'Сурхандарьинская область'), ('Сырдарьинская область', 'Сырдарьинская область'), ('Ташкентская область', 'Ташкентская область'), ('Ферганская область', 'Ферганская область'), ('Хорезмская область', 'Хорезмская область'), ('Республика Каракалпакстан', 'Республика Каракалпакстан'), ('Город Ташкент', 'Город Ташкент')], max_length=255, verbose_name='State')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Performed', 'Performed'), ('Canseled', 'Canseled'), ('Paid', 'Paid')], max_length=255, verbose_name='Status')),
                ('tel', models.CharField(max_length=13, validators=[order.models.telephone_validator], verbose_name='Tel. number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Qty')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productvariants')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Ip')),
                ('forw_ip', models.GenericIPAddressField(verbose_name='Forwarded Ip')),
                ('user_agent', models.CharField(max_length=255, verbose_name='User Agent')),
                ('lng', models.CharField(max_length=255, verbose_name='Accept Language')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
