# Generated by Django 4.1 on 2022-11-30 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 21, 39, 43, 366542), verbose_name='Date'),
        ),
    ]
