# Generated by Django 4.1 on 2022-12-01 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_date_alter_orderhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 16, 16, 53, 908025), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 16, 16, 53, 908025), verbose_name='Date'),
        ),
    ]
