# Generated by Django 4.1 on 2022-12-01 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_promocode_alter_order_date_alter_orderhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.promocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 16, 56, 19, 956796), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 16, 56, 19, 957798), verbose_name='Date'),
        ),
    ]
