# Generated by Django 4.1 on 2022-12-01 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_session_alter_order_date_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='forw_ip',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 58, 29, 140960), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 58, 29, 141959), verbose_name='Date'),
        ),
    ]
