# Generated by Django 4.1 on 2022-12-03 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_update_date_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 5, 40, 749581, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Ожидание модерации', 'Ожидание модерации'), ('Ожидание сборки', 'Ожидание сборки'), ('На доставке', 'На доставке'), ('Отменено', 'Отменено'), ('Доставлено', 'Доставлено')], default='Accepted', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 11, 5, 40, 749581, tzinfo=datetime.timezone.utc), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 5, 40, 749581, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='PaymentTyps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.paymenttyps')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.paymenttyps'),
        ),
    ]
