# Generated by Django 4.1 on 2022-12-03 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_date_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 7, 14, 892910, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=255, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 11, 7, 14, 892910, tzinfo=datetime.timezone.utc), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 7, 14, 892910, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
