# Generated by Django 4.1 on 2022-12-03 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_date_alter_order_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 23, 7, 817356, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.paymenttyps'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 11, 23, 7, 817356, tzinfo=datetime.timezone.utc), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 23, 7, 817356, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
