# Generated by Django 4.1 on 2022-12-07 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_order_date_alter_order_update_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Status name')),
                ('class_name', models.CharField(choices=[('wait', 'wait'), ('moderation_wait', 'moderation_wait'), ('konstruct_wait', 'konstruct_wait'), ('delivery', 'delivery'), ('cansel', 'cansel'), ('delivered', 'delivered')], max_length=255, verbose_name='Css Class Name')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Курьером до двери', 'Курьером до двери')], default='Самовывоз', max_length=255, verbose_name='Shipping type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 38, 42, 330953), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 38, 42, 330953), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 12, 38, 42, 330953, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
