# Generated by Django 4.1 on 2022-12-07 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_order_status_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 49, 15, 687464), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Ожидание модерации', 'Ожидание модерации'), ('Ожидание сборки', 'Ожидание сборки'), ('На доставке', 'На доставке'), ('Отменено', 'Отменено'), ('Доставлено', 'Доставлено')], default='Accepted', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 49, 15, 687464), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 12, 49, 15, 687464, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
