# Generated by Django 4.1 on 2022-12-07 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_order_date_alter_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 49, 41, 2774), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 17, 49, 41, 2774), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 12, 49, 41, 3770, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
