# Generated by Django 4.1 on 2022-12-21 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_productvariants_rating'),
        ('order', '0071_delete_somemodel_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 18, 27, 27, 485589), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 18, 27, 27, 485589), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 13, 27, 27, 486596, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='OrderAplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Product count')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productvariants')),
            ],
        ),
    ]
