# Generated by Django 4.1 on 2022-12-21 13:29

import datetime
from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_alter_order_date_alter_order_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaplication',
            name='last_name',
            field=models.CharField(default='Some', max_length=255, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaplication',
            name='name',
            field=models.CharField(default='Some', max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaplication',
            name='nbm',
            field=models.CharField(default='+998910028174', max_length=13, validators=[order.models.telephone_validator], verbose_name='Tel. nbm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaplication',
            name='patronymic',
            field=models.CharField(default='Some', max_length=255, verbose_name='Patr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 18, 28, 43, 357434), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 18, 28, 43, 357434), verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 13, 28, 43, 358417, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
